### ISSUE TITLE
Lua API

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#19]
This is for both discussion and implementation of the Lua API, which is needed for scripting scenarios and campaigns in mainline and UMC

(will update updated frequently, as discussion goes on)

**Comment by Pentarctagon** [comment]
Having something like https://keplerproject.github.io/luadoc/ which could generate documentation would be useful, I think.

**Comment by Byteron** [comment]
@zozer was asking for a mockup of how lua should be used to have an orientation. Might be good to add that here.

**Comment by Pentarctagon** [comment]
To add to this, and as I've mentioned elsewhere, the one real absolute requirement of the lua API is that is has to be sandboxed, which means that there should be no lua functionality available to UMC that allows directly affecting the system running Wesnoth.

For example - there can't be  ability to use lua's provided file I/O; no ability, through Wesnoth or lua APIs, to read or write files outside Wesnoth's install and add-on directories; no ability to do network I/O; no ability to start any sort of separate process; and so on.

There are also other C++ lua bindings, so perhaps it might be useful to use one of those, since we can't re-use any of Wesnoth 1's code.

**Comment by Byteron** [comment]
Since we plan on using GDScript, Lua is not needed anymore.
This may be reopened when Lua becomes a thing again.
