### ISSUE TITLE
Quit/escape menu button in map editor/scenario

### ISSUE THREAD

**Issue by LawnCable** [wesnoth/haldric#49]
Especially for Mobile and touchscreen-only devices.
related to #45

**Comment by Byteron** [comment]
We definitely should think about the Interface for mobile devices.
ideally we design it so that it works well on both PC and mobile devices, if that's possible.
Side Note: just a few hours ago I exported a test build for android. Input was pretty bad naturally but I was surprised it ran fine otherwise.

**Comment by Byteron** [comment]
fixed by commit a6aba55
