### ISSUE TITLE
Pause menu improvements

### ISSUE THREAD

**Issue by LawnCable** [wesnoth/haldric#52]
- [ ] Add a backdrop to make it clear that the game is paused
- [ ] Painting in the mapeditor should not be possible while pause is active 
- [ ] Currently moving units should pause 
- [ ] and mouse hovering should not select/highlight anything

for Idle animations, they could continue to play, but they could also pause, I don't know which one is better :smile:  - let's discuss it below.

**Comment by Byteron** [comment]
I do agree that the map should not receive any input when the pause menu is open, but I think stopping any processes is a bad idea, since this will be played in multiplayer as well.
if units are currently walking when opening the pause menu, they should finish their moves.
no further input shall be received though.

The backdrop is a good idea.
