### ISSUE TITLE
Long Initial Load on Test Scenario

### ISSUE THREAD

**Issue by LawnCable** [wesnoth/haldric#53]
The first load of the scenario takes long: after the progress bar is finished it takes up to 15 seconds until its loaded, if we need that time, a second progress bar for these additional would be appreciated. 
When I quit to the main menu and open it again, I see the level nearly directly after the progress bar reaches 100%.

**Comment by Byteron** [comment]
Can you check your profiler on what's taking so long?
On my machine loading the scenario takes not longer than 1.5 seconds. Thus, 15 seconds sound way more than it should be.
Also, it should not have different loading times when restarting the scenario, since we don't cache anything. 

If you don't know how the profiler works, here's a tutorial for you:
https://www.youtube.com/watch?v=Yiew9ru-6a0

**Comment by LawnCable** [comment]
I fount nothing with the profiler yesterday thats why I opened this issue, because i think it's probably an " "non blocking" action, because in that 15 seconds additional loadtime I have the full 55-60fps.

**Comment by LawnCable** [comment]
The map editor loads right away, it doesn't have this problem.

**Comment by Byteron** [comment]
The loading bar indeed only shows 100% when the Game.tscn is finished loading.
However, `_ready()` from Game.tscn is where the actual Scenario is instanciated.
Meaning that the whole scenario is loaded after the loading bar reached 100%.
We need to add that loading process to the loading bar too.

The loading bar right now is a temporary thing and will be replaced with a proper loading screen.
We'll address this issue once we get to the loading screen.

**Comment by Byteron** [comment]
Is this issue still present?
Otherwise I'll close this.
