### ISSUE TITLE
AMLA

### ISSUE THREAD

**Issue by Byteron** [wesnoth/haldric#62]
AMLA -> At Max Level Advancement, means, when advancing, the unit type stays the same, but the unit heals and slightly increases both max health and max experience.

There was talk about an overhaul for how AMLA works.
Suggested was a more advanced AMLA system, closer what is implemented for certain characters in UtBS.

Let's discuss.

**Comment by Byteron** [comment]
I've just added AMLA as + 3 Health and +20% experience.
That's just for now though.

**Comment by nemaara** [comment]
1. I think we should keep the AMLA system relatively simple for regular units. In campaigns or MP scenarios we may want to implement, it would be very difficult to balance things (and also doesn't make sense) if the player stacks a bunch of AMLAs on a single unit and makes it extremely powerful. If we do want special units with branching AMLAs (like UtBS), that can be implemented specially for those campaigns/scenarios (and we should have more of that, but reserve it for "hero" units).

2. This isn't to say we need to keep the AMLA system as is. I think we can offer a limited set of AMLAs that make sense for each unit. For example, instead of gaining 3 HP on AMLA, woses could get 5 HP instead, or have an AMLA that increases their regeneration, or we could also offer an AMLA that increases their damage. However, we shouldn't offer both because it makes it very easy to end up with very overpowered units. We also probably shouldn't offer AMLAs that offsets a unit's weaknesses (e.g. no bonus resistance nor bonus defense for the wose) because that can end up making the unit absolutely oppressive with too many AMLAs.

3. I think we should keep the fancier AMLAs for hero units. :)

**Comment by Byteron** [comment]
AMLA as well as normal unit type advancements are now done via the `Advancement` node.
Advancement nodes take `Effect` nodes, which will be applied to the unit when selecting it. This includes an Effect for changing the unit type of the unit, which is used for the normal unit type advancement.
